services:
  scrapper:
    build: .
    container_name: gde-scrapper
    stdin_open: true  # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./downloads:/app/downloads  # Mount downloads directory
      - ./data:/app/data  # Directory for CSV and other data files
    environment:
      - TZ=America/Argentina/Buenos_Aires
    env_file:
      - .env.example
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped
    shm_size: '2gb'  # Increase shared memory for Chrome
    # Add security options for Chrome in Docker
    security_opt:
      - seccomp=unconfined  # Required for Chrome
    cap_add:
      - SYS_ADMIN  # Required for Chrome 