services:
  scrapper:
    build: .
    container_name: gde-scrapper
    stdin_open: true
    tty: true
    volumes:
      - ./downloads:/app/downloads
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - URL=${URL}
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    shm_size: '2gb'
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    restart: "no" 